name: Deploy to Firebase Cloud Functions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  
  env_setup:
    runs-on: ubuntu 
    steps:
    - uses: actions/checkout@v2
  
    - uses: jsdaniell/create-json@1.1.2
      id: create-config-json
      with:
        name: 'serviceAccount.json'
        json: '{"type": "${{ secrets.TYPE }}","auth_uri": "${{ secrets.AUTH_URI }}","auth_provider_x509_cert_url": "${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}","private_key_id": "${{ secrets.PRIVATE_KEY_ID }}","project_id": "${{ secrets.PROJECT_ID }}","private_key": "${{ secrets.PRIVATE_KEY }}","token_uri": "${{ secrets.TOKEN_URI }}", "client_email": "${{ secrets.CLIENT_EMAIL }}","client_x509_cert_url": "${{ secrets.CLIENT_X509_CERT_URL }}","client_id": "${{ secrets.CLIENT_ID }}"}'
        dir: '.'
      
    - name: Create .env.production
      uses: weyheyhey/create-dotenv-action@v1
      with:
        wildecard: "^"
        filename: ".env"
      env:
        ^DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Action for Firebase
      uses: w9jds/firebase-action@v2.0.0
      with:
        args: deploy --only functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_SECRET }}
