name: Deploy to Firebase Cloud Functions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      
      - run: npm ci
      - run: npm run build
      - run: npm prune --production

      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v2.0.0

